dist: xenial
language: python
cache: pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get install pandoc
install:
  - pip install -r requirements/requirements_all.txt
  - python -m spacy download en_core_web_md
script:
  - flake8 alibi
  - mypy alibi
  - travis_wait pytest
  - make build_pypi
  - make build_docs
after_success:
  - codecov
